version: "3.8"
services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - my_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - my_network

networks:
  my_network:

FROM python:3.9
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
CMD ["python", "run.py"]

